### ISSUE TITLE
Idea for site icons

### ISSUE THREAD

**Issue by junewunder** [BarlowProgramming/redirect#20]
I have an idea for the site icons where we can get the website's favicon and make it black and white.  Then use the image for the icon. It would either look good or really not great. This would replace the font awesome icons.

The other way we could make sure icons is by using the first letter of the website name. Example: www.facebook.com would show a picture of an F. This would only be for sites where there's no font awesome icon.

**Comment by junewunder** [comment]
Which do you like more @jlam55555?

**Comment by jlam55555** [comment]
I think the second one would work better, simply because it could be used for any site (as a supplement to FA). The first option would require a similar method to the FontAwesome, in which we would have to store specific favicons; this wouldn't be ideal because creating our own icons is not a great idea (it'll be slow, ugly, and probably not scalable) and it'll increase load time (more http requests).

**Comment by junewunder** [comment]
I agree. Okay I'll start getting on this then,  awesome.
